//Copyright 2014 - 2026 Free Software Foundation, Inc.
//Copyright 2026 VIPS International Pty Ltd
//This file is part of VIPS Mobile
//SPDX - License - Identifier: GPL - 2.0 - or - later

Ext.define('VIPSMobile.model.CallFlowNode', {
    extend: 'Ext.data.Model',
    alternateClassName: ['CallFlowNode'],

    config: {

        idProperty: 'CallFlowID',

        fields: [
            { name: 'CalculatedValueSQL', type: 'string' },
            { name: 'CallFlowID', type: 'integer' },
            { name: 'Colour', type: 'integer' },
            { name: 'CustNo', type: 'integer' },
            { name: 'DCNo', type: 'integer' },
            { name: 'DefaultValue', type: 'string' },
            { name: 'Dest1SQL', type: 'string' },
            { name: 'Destination1', type: 'integer' },
            { name: 'Destination2', type: 'integer' },
            { name: 'Description', type: 'string' },
            { name: 'DynamicAsTable', type: 'boolean' },
            { name: 'DynamicListMode', type: 'integer' },
            { name: 'ExcludeFromLoad', type: 'boolean' },
            { name: 'ExcludeFromPrimaryKeyForLoad', type: 'boolean' },
            { name: 'ExcludeFromSave', type: 'boolean' },
            { name: 'ExtraSQLInsertStatement', type: 'string' },
            { name: 'FieldToStoreValue', type: 'string' },
            { name: 'FKColumn', type: 'string' },
            { name: 'Height', type: 'integer' },
            { name: 'Hidden', type: 'boolean' },
            { name: 'InputMethod', type: 'integer' },
            { name: 'IsGlobal', type: 'integer' },
            { name: 'IsPrimaryKey', type: 'boolean' },
            { name: 'IsPrimaryKeyForThisTableOnly', type: 'boolean' },
            { name: 'IsReadOnly', type: 'boolean' },
            { name: 'JavaScript', type: 'string' },
            { name: 'LastChange', type: 'integer' },
            { name: 'LeadingCharacter', type: 'string' },
            { name: 'ListNotFoundText', type: 'string' },
            { name: 'ListSQL', type: 'string' },
            { name: 'MaxInputLength', type: 'integer' },
            { name: 'NarationSQL', type: 'string' },
            { name: 'NodeTypeDesc', type: 'string' },
            { name: 'OnAcceptAction', type: 'integer' },
            { name: 'OverrideLoadPrevDataSQL', type: 'string' },
            { name: 'ReadOnlySQL', type: 'string' },
            { name: 'ReadOnlySQL', type: 'string' },
            { name: 'ReLoadPreviousEntriesOnChange', type: 'boolean' },
            { name: 'ReCalcValueSQLAgainBeforeSave', type: 'boolean' },
            { name: 'RequiredFields', type: 'string' },
            { name: 'SaveAnswerTypes', type: 'integer' },
            { name: 'SaveSuccessDescription', type: 'string' },
            { name: 'SecondaryDescription', type: 'string' },
            { name: 'SkipSaveIFNull', type: 'boolean' },
            { name: 'StorageTable', type: 'string' },
            { name: 'SQLWebReportParams', type: 'string' },
            { name: 'Thumbnail', type: 'string' },
            { name: 'TypeID', type: 'integer' },
            { name: 'ValidationSQL', type: 'string' },
            { name: 'Value', type: 'string' },
            { name: 'Width', type: 'integer' },
            { name: 'commentsField' },
        ]
    },

    statics: {

        AcceptActions: {
            NOACTION: 0,
            USERSETTING: 1,
            NEXT: 2,
            INDEX: 3,
            CART: 4
        },

        Types: {
            StartNode: 1, 1: 'StartNode',
            ListNode: 2, 2: 'ListNode',
            IntegerNode: 3, 3: 'IntegerNode',
            CurrencyNode: 4, 4: 'CurrencyNode',
            DateNode: 5, 5: 'DateNode',
            TimeNode: 6, 6: 'TimeNode',
            HiddenInternalNode: 7, 7: 'HiddenInternalNode',
            HiddenInternalDateNode: 8, 8: 'HiddenInternalDateNode',
            DynamicNode: 9, 9: 'DynamicNode',
            TableNode: 10, 10: 'TableNode',
            LabelNode: 11, 11: 'LabelNode',
            SQLWebReportNode: 12, 12: 'SQLWebReportNode',
            UndoNode: 13, 13: 'UndoNode',
            UndoBelowThisNode: 14, 14: 'UndoBelowThisNode',
            UploadFileNode: 15, 15: 'UploadFileNode',
            TextNode: 16, 16: 'TextNode',
            HiddenInternalTextNode: 17, 17: 'HiddenInternalTextNode',
            TextListNode: 18, 18: 'TextListNode',
            MultiLineTextNode: 19, 19: 'MultiLineTextNode',
            ImageNode: 20, 20: 'ImageNode',
            BulkSubmitNode: 21, 21: 'BulkSubmitNode',
            CustomPanel: 22, 22: 'CustomPanel',
            Signature: 23, 23: 'Signature',
            YesNo: 24, 24: 'YesNo',
            FloatNode: 25, 25: 'FloatNode',
            ProductDetail: 26, 26: 'ProductDetail',
            CartNode: 27, 27: 'CartNode',
            SyncNode: 28, 28: 'SyncNode',
            BarcodeNode: 30, 30: 'BarcodeNode',
            LineChartNode: 31, 31: 'LineChartNode',
            BarChartNode: 32, 32: 'BarChartNode',
            RadarChartNode: 33, 33: 'RadarChartNode',
            PolarChartNode: 34, 34: 'PolarChartNode',
            PieChartNode: 35, 35: 'PieChartNode',
            DoughnutChartNode: 36, 36: 'DoughnutChartNode',
            TableChartNode: 38, 38: 'TableChartNode',
            MapNode: 37, 37: 'MapNode',
            TableChartNode: 38, 38: "TableChartNode",
            RosterChartNode: 39, 39: "RosterChartNode",
            HTMLTextNode: 40, 40: "HTMLTextNode",
            ListsManagerNode: 41, 41: "ListsManagerNode",
            LibraryItemNode: 42, 42: 'LibraryItemNode',
            SearchNode: 43, 43: "SearchNode",
            MultiPickListNode: 44, 44: 'MultiPickListNode',
            CalendarChartNode: 45, 45: "CalendarChartNode",
            HTMLHiddenNode: 46, 46: "HTMLHiddenNode",
            EmailTextNode: 47, 47: 'EmailTextNode',
            PhoneTextNode: 48, 48: 'PhoneTextNode',
            LengthOfTimeNode: 49, 49: 'LengthOfTimeNode',
            LocationNode: 50, 50: 'LocationNode',
            RankNode: 51, 51: 'RankNode',
            GridNode: 52, 52: 'GridNode',
            HTMLLabelNode: 53, 53: 'HTMLLabelNode',
            SortChartNode: 54, 54: 'SortChartNode',
            CalendarExportChartNode: 62, 62: 'CalendarExportChartNode',
            RatingNode: 63, 63: 'RatingNode',
            LabelChartNode: 65, 65: 'LabelChartNode',
            GuageChartNode: 66, 66: 'GuageChartNode',
            ResourceChartNode: 70, 70: "ResourceChartNode",
            SaveNode: 100, 100: 'SaveNode'
        },

        ChartNodeTypes: [31,32,33,34,35,36,38,65,66],

        DynamicListModes: {
            UseAllItemsFromList: 1, 1: 'UseAllItemsFromList',
            UseListItemsAsOptions: 2, 2: 'UseListItemsAsOptions',
            UseManualKeyEntry: 3, 3: 'UseManualKeyEntry',
            UseAllItemsFromListAndAllowManualEntry: 4, 4: 'UseAllItemsFromListAndAllowManualEntry'
        }

    }

});
